#!/bin/bash

LINES=`cat test | wc -l`
#echo "$LINES" >> test
random_number=$((RANDOM % $LINES))

random_number=$((random_number + 1))
sed -n "${random_number}p" "test" | sed 's|\/|\n|g' > quotes.txt
#cat quotes.txt |wc -c
echo " " 
cat quotes.txt
